-- NexusERP Finance — Plan Comptable Général France (PCG)
-- Seed data pour tenant FR

-- Ce script s'exécute uniquement sur le schéma du tenant
-- La variable app.tenant_id doit être définie

-- Classes PCG France
INSERT INTO nexus_finance.chart_of_accounts (tenant_id, account_number, account_name, account_type, is_detail, country)
VALUES
-- Classe 1 — Comptes de capitaux
('system', '1', 'Comptes de capitaux', 'EQUITY', false, 'FR'),
('system', '10', 'Capital et réserves', 'EQUITY', false, 'FR'),
('system', '101', 'Capital social', 'EQUITY', true, 'FR'),
('system', '104', 'Primes liées au capital social', 'EQUITY', true, 'FR'),
('system', '106', 'Réserves', 'EQUITY', false, 'FR'),
('system', '1061', 'Réserve légale', 'EQUITY', true, 'FR'),
('system', '1068', 'Autres réserves', 'EQUITY', true, 'FR'),
('system', '110', 'Report à nouveau (solde créditeur)', 'EQUITY', true, 'FR'),
('system', '119', 'Report à nouveau (solde débiteur)', 'EQUITY', true, 'FR'),
('system', '120', 'Résultat de l''exercice (bénéfice)', 'EQUITY', true, 'FR'),
('system', '129', 'Résultat de l''exercice (perte)', 'EQUITY', true, 'FR'),
('system', '13', 'Subventions d''investissement', 'EQUITY', true, 'FR'),
('system', '14', 'Provisions réglementées', 'LIABILITY', false, 'FR'),
('system', '15', 'Provisions', 'LIABILITY', false, 'FR'),
('system', '151', 'Provisions pour risques', 'LIABILITY', true, 'FR'),
('system', '153', 'Provisions pour pensions et obligations similaires', 'LIABILITY', true, 'FR'),
('system', '155', 'Provisions pour impôts', 'LIABILITY', true, 'FR'),
('system', '16', 'Emprunts et dettes assimilées', 'LIABILITY', false, 'FR'),
('system', '164', 'Emprunts auprès des établissements de crédit', 'LIABILITY', true, 'FR'),
('system', '165', 'Dépôts et cautionnements reçus', 'LIABILITY', true, 'FR'),
('system', '168', 'Intérêts courus', 'LIABILITY', true, 'FR'),

-- Classe 2 — Comptes d''immobilisations
('system', '2', 'Comptes d''immobilisations', 'ASSET', false, 'FR'),
('system', '20', 'Immobilisations incorporelles', 'ASSET', false, 'FR'),
('system', '201', 'Frais d''établissement', 'ASSET', true, 'FR'),
('system', '203', 'Frais de recherche et développement', 'ASSET', true, 'FR'),
('system', '205', 'Concessions, brevets, licences, marques', 'ASSET', true, 'FR'),
('system', '207', 'Fonds commercial', 'ASSET', true, 'FR'),
('system', '21', 'Immobilisations corporelles', 'ASSET', false, 'FR'),
('system', '211', 'Terrains', 'ASSET', true, 'FR'),
('system', '212', 'Agencements et aménagements de terrains', 'ASSET', true, 'FR'),
('system', '213', 'Constructions', 'ASSET', true, 'FR'),
('system', '215', 'Installations techniques, matériel et outillage industriels', 'ASSET', true, 'FR'),
('system', '218', 'Autres immobilisations corporelles', 'ASSET', true, 'FR'),
('system', '22', 'Immobilisations mises en concession', 'ASSET', true, 'FR'),
('system', '23', 'Immobilisations en cours', 'ASSET', true, 'FR'),
('system', '26', 'Participations et créances rattachées', 'ASSET', false, 'FR'),
('system', '261', 'Titres de participation', 'ASSET', true, 'FR'),
('system', '27', 'Autres immobilisations financières', 'ASSET', false, 'FR'),
('system', '271', 'Titres immobilisés (droit de propriété)', 'ASSET', true, 'FR'),
('system', '274', 'Prêts', 'ASSET', true, 'FR'),
('system', '28', 'Amortissements des immobilisations', 'ASSET', false, 'FR'),
('system', '281', 'Amortissements des immobilisations incorporelles', 'ASSET', true, 'FR'),
('system', '2811', 'Amortissements des frais d''établissement', 'ASSET', true, 'FR'),
('system', '2813', 'Amortissements des frais de R&D', 'ASSET', true, 'FR'),
('system', '282', 'Amortissements des immobilisations corporelles', 'ASSET', true, 'FR'),
('system', '2813', 'Amortissements des constructions', 'ASSET', true, 'FR'),
('system', '2815', 'Amortissements installations techniques', 'ASSET', true, 'FR'),

-- Classe 3 — Comptes de stocks et en-cours
('system', '3', 'Comptes de stocks et en-cours', 'ASSET', false, 'FR'),
('system', '31', 'Matières premières et fournitures', 'ASSET', true, 'FR'),
('system', '32', 'Autres approvisionnements', 'ASSET', true, 'FR'),
('system', '33', 'En-cours de production de biens', 'ASSET', true, 'FR'),
('system', '34', 'En-cours de production de services', 'ASSET', true, 'FR'),
('system', '35', 'Stocks de produits', 'ASSET', true, 'FR'),
('system', '37', 'Stocks de marchandises', 'ASSET', true, 'FR'),
('system', '39', 'Dépréciations des stocks et en-cours', 'ASSET', true, 'FR'),

-- Classe 4 — Comptes de tiers
('system', '4', 'Comptes de tiers', 'ASSET', false, 'FR'),
('system', '40', 'Fournisseurs et comptes rattachés', 'LIABILITY', false, 'FR'),
('system', '401', 'Fournisseurs', 'LIABILITY', true, 'FR'),
('system', '403', 'Fournisseurs - Effets à payer', 'LIABILITY', true, 'FR'),
('system', '408', 'Fournisseurs - Factures non parvenues', 'LIABILITY', true, 'FR'),
('system', '409', 'Fournisseurs débiteurs', 'ASSET', true, 'FR'),
('system', '41', 'Clients et comptes rattachés', 'ASSET', false, 'FR'),
('system', '411', 'Clients', 'ASSET', true, 'FR'),
('system', '413', 'Clients - Effets à recevoir', 'ASSET', true, 'FR'),
('system', '416', 'Clients douteux ou litigieux', 'ASSET', true, 'FR'),
('system', '418', 'Clients - Produits non encore facturés', 'ASSET', true, 'FR'),
('system', '419', 'Clients créditeurs', 'LIABILITY', true, 'FR'),
('system', '42', 'Personnel et comptes rattachés', 'LIABILITY', false, 'FR'),
('system', '421', 'Personnel - Rémunérations dues', 'LIABILITY', true, 'FR'),
('system', '425', 'Personnel - Avances et acomptes', 'ASSET', true, 'FR'),
('system', '431', 'Sécurité sociale', 'LIABILITY', true, 'FR'),
('system', '437', 'Autres organismes sociaux', 'LIABILITY', true, 'FR'),
('system', '44', 'État et autres collectivités publiques', 'LIABILITY', false, 'FR'),
('system', '441', 'État - Subventions à recevoir', 'ASSET', true, 'FR'),
('system', '4452', 'État - TVA due intracommunautaire', 'LIABILITY', true, 'FR'),
('system', '4455', 'Taxes sur le chiffre d''affaires à décaisser', 'LIABILITY', true, 'FR'),
('system', '4456', 'Taxes sur le chiffre d''affaires déductibles', 'ASSET', true, 'FR'),
('system', '4457', 'Taxes sur le chiffre d''affaires collectées', 'LIABILITY', true, 'FR'),
('system', '4458', 'Taxes sur le chiffre d''affaires à régulariser ou en attente', 'ASSET', true, 'FR'),
('system', '447', 'Autres impôts, taxes et versements assimilés', 'LIABILITY', true, 'FR'),
('system', '448', 'État - Charges à payer et produits à recevoir', 'LIABILITY', true, 'FR'),
('system', '45', 'Groupe et associés', 'ASSET', false, 'FR'),
('system', '46', 'Débiteurs divers et créditeurs divers', 'ASSET', false, 'FR'),
('system', '462', 'Créances sur cessions d''immobilisations', 'ASSET', true, 'FR'),
('system', '467', 'Autres comptes débiteurs ou créditeurs', 'ASSET', true, 'FR'),
('system', '48', 'Comptes de régularisation', 'ASSET', false, 'FR'),
('system', '481', 'Charges à répartir sur plusieurs exercices', 'ASSET', true, 'FR'),
('system', '486', 'Charges constatées d''avance', 'ASSET', true, 'FR'),
('system', '487', 'Produits constatés d''avance', 'LIABILITY', true, 'FR'),
('system', '491', 'Dépréciations des comptes de clients', 'ASSET', true, 'FR'),

-- Classe 5 — Comptes financiers
('system', '5', 'Comptes financiers', 'ASSET', false, 'FR'),
('system', '51', 'Banques, établissements financiers et assimilés', 'ASSET', false, 'FR'),
('system', '512', 'Banques', 'ASSET', true, 'FR'),
('system', '514', 'Chèques postaux', 'ASSET', true, 'FR'),
('system', '515', 'Caisses des établissements financiers', 'ASSET', true, 'FR'),
('system', '516', 'Valeurs mobilières de placement', 'ASSET', true, 'FR'),
('system', '53', 'Caisse', 'ASSET', false, 'FR'),
('system', '531', 'Caisse siège social', 'ASSET', true, 'FR'),
('system', '532', 'Caisses des succursales', 'ASSET', true, 'FR'),
('system', '54', 'Régies d''avances et accréditifs', 'ASSET', true, 'FR'),

-- Classe 6 — Comptes de charges
('system', '6', 'Comptes de charges', 'EXPENSE', false, 'FR'),
('system', '60', 'Achats (sauf 603)', 'EXPENSE', false, 'FR'),
('system', '601', 'Achats de matières premières', 'EXPENSE', true, 'FR'),
('system', '602', 'Achats d''autres approvisionnements', 'EXPENSE', true, 'FR'),
('system', '604', 'Achats d''études et prestations de services', 'EXPENSE', true, 'FR'),
('system', '605', 'Achats de matériel, équipements et travaux', 'EXPENSE', true, 'FR'),
('system', '606', 'Achats non stockés de matières et fournitures', 'EXPENSE', true, 'FR'),
('system', '607', 'Achats de marchandises', 'EXPENSE', true, 'FR'),
('system', '608', 'Frais accessoires sur achats', 'EXPENSE', true, 'FR'),
('system', '609', 'Rabais, remises et ristournes obtenus sur achats', 'EXPENSE', true, 'FR'),
('system', '61', 'Services extérieurs', 'EXPENSE', false, 'FR'),
('system', '611', 'Sous-traitance générale', 'EXPENSE', true, 'FR'),
('system', '612', 'Redevances de crédit-bail', 'EXPENSE', true, 'FR'),
('system', '613', 'Locations', 'EXPENSE', true, 'FR'),
('system', '614', 'Charges locatives et de copropriété', 'EXPENSE', true, 'FR'),
('system', '615', 'Entretiens et réparations', 'EXPENSE', true, 'FR'),
('system', '616', 'Primes d''assurances', 'EXPENSE', true, 'FR'),
('system', '617', 'Études et recherches', 'EXPENSE', true, 'FR'),
('system', '618', 'Divers', 'EXPENSE', true, 'FR'),
('system', '62', 'Autres services extérieurs', 'EXPENSE', false, 'FR'),
('system', '621', 'Personnel extérieur à l''entreprise', 'EXPENSE', true, 'FR'),
('system', '622', 'Rémunérations d''intermédiaires et honoraires', 'EXPENSE', true, 'FR'),
('system', '623', 'Publicité, publications, relations publiques', 'EXPENSE', true, 'FR'),
('system', '624', 'Transports de biens et transports collectifs du personnel', 'EXPENSE', true, 'FR'),
('system', '625', 'Déplacements, missions et réceptions', 'EXPENSE', true, 'FR'),
('system', '626', 'Frais postaux et de télécommunications', 'EXPENSE', true, 'FR'),
('system', '627', 'Services bancaires et assimilés', 'EXPENSE', true, 'FR'),
('system', '628', 'Divers', 'EXPENSE', true, 'FR'),
('system', '63', 'Impôts, taxes et versements assimilés', 'EXPENSE', false, 'FR'),
('system', '631', 'Impôts, taxes et versements sur rémunérations', 'EXPENSE', true, 'FR'),
('system', '635', 'Autres impôts, taxes et versements assimilés', 'EXPENSE', true, 'FR'),
('system', '64', 'Charges de personnel', 'EXPENSE', false, 'FR'),
('system', '641', 'Rémunérations du personnel', 'EXPENSE', true, 'FR'),
('system', '645', 'Charges de sécurité sociale et de prévoyance', 'EXPENSE', true, 'FR'),
('system', '647', 'Autres charges sociales', 'EXPENSE', true, 'FR'),
('system', '648', 'Autres charges de personnel', 'EXPENSE', true, 'FR'),
('system', '65', 'Autres charges de gestion courante', 'EXPENSE', false, 'FR'),
('system', '651', 'Redevances pour concessions, brevets, licences', 'EXPENSE', true, 'FR'),
('system', '654', 'Pertes sur créances irrécouvrables', 'EXPENSE', true, 'FR'),
('system', '66', 'Charges financières', 'EXPENSE', false, 'FR'),
('system', '661', 'Charges d''intérêts', 'EXPENSE', true, 'FR'),
('system', '664', 'Pertes sur créances liées à des participations', 'EXPENSE', true, 'FR'),
('system', '665', 'Escomptes accordés', 'EXPENSE', true, 'FR'),
('system', '666', 'Pertes de change', 'EXPENSE', true, 'FR'),
('system', '67', 'Charges exceptionnelles', 'EXPENSE', false, 'FR'),
('system', '671', 'Charges exceptionnelles sur opérations de gestion', 'EXPENSE', true, 'FR'),
('system', '675', 'Valeurs comptables des éléments d''actif cédés', 'EXPENSE', true, 'FR'),
('system', '68', 'Dotations aux amortissements, dépréciations et provisions', 'EXPENSE', false, 'FR'),
('system', '681', 'Dotations aux amortissements, dépréciations et provisions exploitation', 'EXPENSE', true, 'FR'),
('system', '686', 'Dotations aux amortissements, dépréciations et provisions financières', 'EXPENSE', true, 'FR'),
('system', '69', 'Participation des salariés - Impôts sur les bénéfices', 'EXPENSE', true, 'FR'),

-- Classe 7 — Comptes de produits
('system', '7', 'Comptes de produits', 'REVENUE', false, 'FR'),
('system', '70', 'Ventes de produits fabriqués, prestations de services, marchandises', 'REVENUE', false, 'FR'),
('system', '701', 'Ventes de produits finis', 'REVENUE', true, 'FR'),
('system', '702', 'Ventes de produits intermédiaires', 'REVENUE', true, 'FR'),
('system', '703', 'Ventes de produits résiduels', 'REVENUE', true, 'FR'),
('system', '704', 'Travaux', 'REVENUE', true, 'FR'),
('system', '705', 'Études', 'REVENUE', true, 'FR'),
('system', '706', 'Prestations de services', 'REVENUE', true, 'FR'),
('system', '707', 'Ventes de marchandises', 'REVENUE', true, 'FR'),
('system', '708', 'Produits des activités annexes', 'REVENUE', true, 'FR'),
('system', '709', 'Rabais, remises et ristournes accordés par l''entreprise', 'REVENUE', true, 'FR'),
('system', '71', 'Production stockée (ou déstockage)', 'REVENUE', true, 'FR'),
('system', '72', 'Production immobilisée', 'REVENUE', true, 'FR'),
('system', '74', 'Subventions d''exploitation', 'REVENUE', true, 'FR'),
('system', '75', 'Autres produits de gestion courante', 'REVENUE', false, 'FR'),
('system', '751', 'Redevances pour concessions, brevets, licences', 'REVENUE', true, 'FR'),
('system', '755', 'Quotes-parts de résultat sur opérations faites en commun', 'REVENUE', true, 'FR'),
('system', '76', 'Produits financiers', 'REVENUE', false, 'FR'),
('system', '761', 'Produits de participations', 'REVENUE', true, 'FR'),
('system', '764', 'Revenus des valeurs mobilières de placement', 'REVENUE', true, 'FR'),
('system', '765', 'Escomptes obtenus', 'REVENUE', true, 'FR'),
('system', '766', 'Gains de change', 'REVENUE', true, 'FR'),
('system', '77', 'Produits exceptionnels', 'REVENUE', false, 'FR'),
('system', '771', 'Produits exceptionnels sur opérations de gestion', 'REVENUE', true, 'FR'),
('system', '775', 'Produits des cessions d''éléments d''actif', 'REVENUE', true, 'FR'),
('system', '78', 'Reprises sur amortissements, dépréciations et provisions', 'REVENUE', false, 'FR'),
('system', '781', 'Reprises sur amortissements, dépréciations et provisions d''exploitation', 'REVENUE', true, 'FR')

ON CONFLICT (tenant_id, account_number) DO NOTHING;
